server:
  port: 8083

spring:
  application:
    name: authentication-8083

  cloud:
    consul:
      host: 4.233.150.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3333
    url: jdbc:mysql://mysql_back:3306/microservices
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

logging:
  level:
    com.cloud.spring.controller: debug

springdoc:
  api-docs:
    path: /auth/api-doc