server:
  port: 8084

grpc:
  server:
    port: 9091

spring:
  application:
    name: product-8084

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3333
    url: jdbc:mysql://mysql_back:3306/microservices

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true


  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
      host: consul_back
      port: 8500


springdoc:
  api-docs:
    path: /product/api-doc
